# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Raytracer_config = debug
endif
ifeq ($(config),release)
  Raytracer_config = release
endif

PROJECTS := Raytracer

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Raytracer:
ifneq (,$(Raytracer_config))
	@echo "==== Building Raytracer ($(Raytracer_config)) ===="
	@${MAKE} --no-print-directory -C . -f Raytracer.make config=$(Raytracer_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f Raytracer.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Raytracer"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"