# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tarek/raytracer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tarek/raytracer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tarek/raytracer/CMakeFiles /home/tarek/raytracer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tarek/raytracer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Raytracer

# Build rule for target.
Raytracer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Raytracer
.PHONY : Raytracer

# fast build rule for target.
Raytracer/fast:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/build
.PHONY : Raytracer/fast

src/AABB.o: src/AABB.cpp.o

.PHONY : src/AABB.o

# target to build an object file
src/AABB.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/AABB.cpp.o
.PHONY : src/AABB.cpp.o

src/AABB.i: src/AABB.cpp.i

.PHONY : src/AABB.i

# target to preprocess a source file
src/AABB.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/AABB.cpp.i
.PHONY : src/AABB.cpp.i

src/AABB.s: src/AABB.cpp.s

.PHONY : src/AABB.s

# target to generate assembly for a file
src/AABB.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/AABB.cpp.s
.PHONY : src/AABB.cpp.s

src/AsyncRenderData.o: src/AsyncRenderData.cpp.o

.PHONY : src/AsyncRenderData.o

# target to build an object file
src/AsyncRenderData.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/AsyncRenderData.cpp.o
.PHONY : src/AsyncRenderData.cpp.o

src/AsyncRenderData.i: src/AsyncRenderData.cpp.i

.PHONY : src/AsyncRenderData.i

# target to preprocess a source file
src/AsyncRenderData.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/AsyncRenderData.cpp.i
.PHONY : src/AsyncRenderData.cpp.i

src/AsyncRenderData.s: src/AsyncRenderData.cpp.s

.PHONY : src/AsyncRenderData.s

# target to generate assembly for a file
src/AsyncRenderData.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/AsyncRenderData.cpp.s
.PHONY : src/AsyncRenderData.cpp.s

src/Camera.o: src/Camera.cpp.o

.PHONY : src/Camera.o

# target to build an object file
src/Camera.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Camera.cpp.o
.PHONY : src/Camera.cpp.o

src/Camera.i: src/Camera.cpp.i

.PHONY : src/Camera.i

# target to preprocess a source file
src/Camera.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Camera.cpp.i
.PHONY : src/Camera.cpp.i

src/Camera.s: src/Camera.cpp.s

.PHONY : src/Camera.s

# target to generate assembly for a file
src/Camera.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Camera.cpp.s
.PHONY : src/Camera.cpp.s

src/GroupPanel.o: src/GroupPanel.cpp.o

.PHONY : src/GroupPanel.o

# target to build an object file
src/GroupPanel.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/GroupPanel.cpp.o
.PHONY : src/GroupPanel.cpp.o

src/GroupPanel.i: src/GroupPanel.cpp.i

.PHONY : src/GroupPanel.i

# target to preprocess a source file
src/GroupPanel.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/GroupPanel.cpp.i
.PHONY : src/GroupPanel.cpp.i

src/GroupPanel.s: src/GroupPanel.cpp.s

.PHONY : src/GroupPanel.s

# target to generate assembly for a file
src/GroupPanel.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/GroupPanel.cpp.s
.PHONY : src/GroupPanel.cpp.s

src/HittableList.o: src/HittableList.cpp.o

.PHONY : src/HittableList.o

# target to build an object file
src/HittableList.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/HittableList.cpp.o
.PHONY : src/HittableList.cpp.o

src/HittableList.i: src/HittableList.cpp.i

.PHONY : src/HittableList.i

# target to preprocess a source file
src/HittableList.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/HittableList.cpp.i
.PHONY : src/HittableList.cpp.i

src/HittableList.s: src/HittableList.cpp.s

.PHONY : src/HittableList.s

# target to generate assembly for a file
src/HittableList.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/HittableList.cpp.s
.PHONY : src/HittableList.cpp.s

src/Ray.o: src/Ray.cpp.o

.PHONY : src/Ray.o

# target to build an object file
src/Ray.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Ray.cpp.o
.PHONY : src/Ray.cpp.o

src/Ray.i: src/Ray.cpp.i

.PHONY : src/Ray.i

# target to preprocess a source file
src/Ray.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Ray.cpp.i
.PHONY : src/Ray.cpp.i

src/Ray.s: src/Ray.cpp.s

.PHONY : src/Ray.s

# target to generate assembly for a file
src/Ray.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Ray.cpp.s
.PHONY : src/Ray.cpp.s

src/RenderAsync.o: src/RenderAsync.cpp.o

.PHONY : src/RenderAsync.o

# target to build an object file
src/RenderAsync.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/RenderAsync.cpp.o
.PHONY : src/RenderAsync.cpp.o

src/RenderAsync.i: src/RenderAsync.cpp.i

.PHONY : src/RenderAsync.i

# target to preprocess a source file
src/RenderAsync.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/RenderAsync.cpp.i
.PHONY : src/RenderAsync.cpp.i

src/RenderAsync.s: src/RenderAsync.cpp.s

.PHONY : src/RenderAsync.s

# target to generate assembly for a file
src/RenderAsync.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/RenderAsync.cpp.s
.PHONY : src/RenderAsync.cpp.s

src/Scene.o: src/Scene.cpp.o

.PHONY : src/Scene.o

# target to build an object file
src/Scene.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Scene.cpp.o
.PHONY : src/Scene.cpp.o

src/Scene.i: src/Scene.cpp.i

.PHONY : src/Scene.i

# target to preprocess a source file
src/Scene.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Scene.cpp.i
.PHONY : src/Scene.cpp.i

src/Scene.s: src/Scene.cpp.s

.PHONY : src/Scene.s

# target to generate assembly for a file
src/Scene.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Scene.cpp.s
.PHONY : src/Scene.cpp.s

src/Transformation.o: src/Transformation.cpp.o

.PHONY : src/Transformation.o

# target to build an object file
src/Transformation.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Transformation.cpp.o
.PHONY : src/Transformation.cpp.o

src/Transformation.i: src/Transformation.cpp.i

.PHONY : src/Transformation.i

# target to preprocess a source file
src/Transformation.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Transformation.cpp.i
.PHONY : src/Transformation.cpp.i

src/Transformation.s: src/Transformation.cpp.s

.PHONY : src/Transformation.s

# target to generate assembly for a file
src/Transformation.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/Transformation.cpp.s
.PHONY : src/Transformation.cpp.s

src/app.o: src/app.cpp.o

.PHONY : src/app.o

# target to build an object file
src/app.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/app.cpp.o
.PHONY : src/app.cpp.o

src/app.i: src/app.cpp.i

.PHONY : src/app.i

# target to preprocess a source file
src/app.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/app.cpp.i
.PHONY : src/app.cpp.i

src/app.s: src/app.cpp.s

.PHONY : src/app.s

# target to generate assembly for a file
src/app.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/app.cpp.s
.PHONY : src/app.cpp.s

src/data_structures/vec3.o: src/data_structures/vec3.cpp.o

.PHONY : src/data_structures/vec3.o

# target to build an object file
src/data_structures/vec3.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/data_structures/vec3.cpp.o
.PHONY : src/data_structures/vec3.cpp.o

src/data_structures/vec3.i: src/data_structures/vec3.cpp.i

.PHONY : src/data_structures/vec3.i

# target to preprocess a source file
src/data_structures/vec3.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/data_structures/vec3.cpp.i
.PHONY : src/data_structures/vec3.cpp.i

src/data_structures/vec3.s: src/data_structures/vec3.cpp.s

.PHONY : src/data_structures/vec3.s

# target to generate assembly for a file
src/data_structures/vec3.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/data_structures/vec3.cpp.s
.PHONY : src/data_structures/vec3.cpp.s

src/editor/Utils.o: src/editor/Utils.cpp.o

.PHONY : src/editor/Utils.o

# target to build an object file
src/editor/Utils.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/editor/Utils.cpp.o
.PHONY : src/editor/Utils.cpp.o

src/editor/Utils.i: src/editor/Utils.cpp.i

.PHONY : src/editor/Utils.i

# target to preprocess a source file
src/editor/Utils.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/editor/Utils.cpp.i
.PHONY : src/editor/Utils.cpp.i

src/editor/Utils.s: src/editor/Utils.cpp.s

.PHONY : src/editor/Utils.s

# target to generate assembly for a file
src/editor/Utils.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/editor/Utils.cpp.s
.PHONY : src/editor/Utils.cpp.s

src/editor/editor.o: src/editor/editor.cpp.o

.PHONY : src/editor/editor.o

# target to build an object file
src/editor/editor.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/editor/editor.cpp.o
.PHONY : src/editor/editor.cpp.o

src/editor/editor.i: src/editor/editor.cpp.i

.PHONY : src/editor/editor.i

# target to preprocess a source file
src/editor/editor.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/editor/editor.cpp.i
.PHONY : src/editor/editor.cpp.i

src/editor/editor.s: src/editor/editor.cpp.s

.PHONY : src/editor/editor.s

# target to generate assembly for a file
src/editor/editor.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/editor/editor.cpp.s
.PHONY : src/editor/editor.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/objects/AARect.o: src/objects/AARect.cpp.o

.PHONY : src/objects/AARect.o

# target to build an object file
src/objects/AARect.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/objects/AARect.cpp.o
.PHONY : src/objects/AARect.cpp.o

src/objects/AARect.i: src/objects/AARect.cpp.i

.PHONY : src/objects/AARect.i

# target to preprocess a source file
src/objects/AARect.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/objects/AARect.cpp.i
.PHONY : src/objects/AARect.cpp.i

src/objects/AARect.s: src/objects/AARect.cpp.s

.PHONY : src/objects/AARect.s

# target to generate assembly for a file
src/objects/AARect.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/objects/AARect.cpp.s
.PHONY : src/objects/AARect.cpp.s

src/objects/Box.o: src/objects/Box.cpp.o

.PHONY : src/objects/Box.o

# target to build an object file
src/objects/Box.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/objects/Box.cpp.o
.PHONY : src/objects/Box.cpp.o

src/objects/Box.i: src/objects/Box.cpp.i

.PHONY : src/objects/Box.i

# target to preprocess a source file
src/objects/Box.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/objects/Box.cpp.i
.PHONY : src/objects/Box.cpp.i

src/objects/Box.s: src/objects/Box.cpp.s

.PHONY : src/objects/Box.s

# target to generate assembly for a file
src/objects/Box.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/objects/Box.cpp.s
.PHONY : src/objects/Box.cpp.s

src/objects/Sphere.o: src/objects/Sphere.cpp.o

.PHONY : src/objects/Sphere.o

# target to build an object file
src/objects/Sphere.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/objects/Sphere.cpp.o
.PHONY : src/objects/Sphere.cpp.o

src/objects/Sphere.i: src/objects/Sphere.cpp.i

.PHONY : src/objects/Sphere.i

# target to preprocess a source file
src/objects/Sphere.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/objects/Sphere.cpp.i
.PHONY : src/objects/Sphere.cpp.i

src/objects/Sphere.s: src/objects/Sphere.cpp.s

.PHONY : src/objects/Sphere.s

# target to generate assembly for a file
src/objects/Sphere.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/src/objects/Sphere.cpp.s
.PHONY : src/objects/Sphere.cpp.s

vendor/ImGuiFileDialog/ImGuiFileDialog.o: vendor/ImGuiFileDialog/ImGuiFileDialog.cpp.o

.PHONY : vendor/ImGuiFileDialog/ImGuiFileDialog.o

# target to build an object file
vendor/ImGuiFileDialog/ImGuiFileDialog.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/vendor/ImGuiFileDialog/ImGuiFileDialog.cpp.o
.PHONY : vendor/ImGuiFileDialog/ImGuiFileDialog.cpp.o

vendor/ImGuiFileDialog/ImGuiFileDialog.i: vendor/ImGuiFileDialog/ImGuiFileDialog.cpp.i

.PHONY : vendor/ImGuiFileDialog/ImGuiFileDialog.i

# target to preprocess a source file
vendor/ImGuiFileDialog/ImGuiFileDialog.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/vendor/ImGuiFileDialog/ImGuiFileDialog.cpp.i
.PHONY : vendor/ImGuiFileDialog/ImGuiFileDialog.cpp.i

vendor/ImGuiFileDialog/ImGuiFileDialog.s: vendor/ImGuiFileDialog/ImGuiFileDialog.cpp.s

.PHONY : vendor/ImGuiFileDialog/ImGuiFileDialog.s

# target to generate assembly for a file
vendor/ImGuiFileDialog/ImGuiFileDialog.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/vendor/ImGuiFileDialog/ImGuiFileDialog.cpp.s
.PHONY : vendor/ImGuiFileDialog/ImGuiFileDialog.cpp.s

vendor/argumentum/src/argparser.o: vendor/argumentum/src/argparser.cpp.o

.PHONY : vendor/argumentum/src/argparser.o

# target to build an object file
vendor/argumentum/src/argparser.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/vendor/argumentum/src/argparser.cpp.o
.PHONY : vendor/argumentum/src/argparser.cpp.o

vendor/argumentum/src/argparser.i: vendor/argumentum/src/argparser.cpp.i

.PHONY : vendor/argumentum/src/argparser.i

# target to preprocess a source file
vendor/argumentum/src/argparser.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/vendor/argumentum/src/argparser.cpp.i
.PHONY : vendor/argumentum/src/argparser.cpp.i

vendor/argumentum/src/argparser.s: vendor/argumentum/src/argparser.cpp.s

.PHONY : vendor/argumentum/src/argparser.s

# target to generate assembly for a file
vendor/argumentum/src/argparser.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/vendor/argumentum/src/argparser.cpp.s
.PHONY : vendor/argumentum/src/argparser.cpp.s

vendor/imguizmo/ImGuizmo.o: vendor/imguizmo/ImGuizmo.cpp.o

.PHONY : vendor/imguizmo/ImGuizmo.o

# target to build an object file
vendor/imguizmo/ImGuizmo.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/vendor/imguizmo/ImGuizmo.cpp.o
.PHONY : vendor/imguizmo/ImGuizmo.cpp.o

vendor/imguizmo/ImGuizmo.i: vendor/imguizmo/ImGuizmo.cpp.i

.PHONY : vendor/imguizmo/ImGuizmo.i

# target to preprocess a source file
vendor/imguizmo/ImGuizmo.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/vendor/imguizmo/ImGuizmo.cpp.i
.PHONY : vendor/imguizmo/ImGuizmo.cpp.i

vendor/imguizmo/ImGuizmo.s: vendor/imguizmo/ImGuizmo.cpp.s

.PHONY : vendor/imguizmo/ImGuizmo.s

# target to generate assembly for a file
vendor/imguizmo/ImGuizmo.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/vendor/imguizmo/ImGuizmo.cpp.s
.PHONY : vendor/imguizmo/ImGuizmo.cpp.s

vendor/rlImGui/imgui/backends/imgui_impl_opengl3.o: vendor/rlImGui/imgui/backends/imgui_impl_opengl3.cpp.o

.PHONY : vendor/rlImGui/imgui/backends/imgui_impl_opengl3.o

# target to build an object file
vendor/rlImGui/imgui/backends/imgui_impl_opengl3.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/vendor/rlImGui/imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : vendor/rlImGui/imgui/backends/imgui_impl_opengl3.cpp.o

vendor/rlImGui/imgui/backends/imgui_impl_opengl3.i: vendor/rlImGui/imgui/backends/imgui_impl_opengl3.cpp.i

.PHONY : vendor/rlImGui/imgui/backends/imgui_impl_opengl3.i

# target to preprocess a source file
vendor/rlImGui/imgui/backends/imgui_impl_opengl3.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/vendor/rlImGui/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : vendor/rlImGui/imgui/backends/imgui_impl_opengl3.cpp.i

vendor/rlImGui/imgui/backends/imgui_impl_opengl3.s: vendor/rlImGui/imgui/backends/imgui_impl_opengl3.cpp.s

.PHONY : vendor/rlImGui/imgui/backends/imgui_impl_opengl3.s

# target to generate assembly for a file
vendor/rlImGui/imgui/backends/imgui_impl_opengl3.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/vendor/rlImGui/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : vendor/rlImGui/imgui/backends/imgui_impl_opengl3.cpp.s

vendor/rlImGui/imgui/imgui.o: vendor/rlImGui/imgui/imgui.cpp.o

.PHONY : vendor/rlImGui/imgui/imgui.o

# target to build an object file
vendor/rlImGui/imgui/imgui.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/vendor/rlImGui/imgui/imgui.cpp.o
.PHONY : vendor/rlImGui/imgui/imgui.cpp.o

vendor/rlImGui/imgui/imgui.i: vendor/rlImGui/imgui/imgui.cpp.i

.PHONY : vendor/rlImGui/imgui/imgui.i

# target to preprocess a source file
vendor/rlImGui/imgui/imgui.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/vendor/rlImGui/imgui/imgui.cpp.i
.PHONY : vendor/rlImGui/imgui/imgui.cpp.i

vendor/rlImGui/imgui/imgui.s: vendor/rlImGui/imgui/imgui.cpp.s

.PHONY : vendor/rlImGui/imgui/imgui.s

# target to generate assembly for a file
vendor/rlImGui/imgui/imgui.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/vendor/rlImGui/imgui/imgui.cpp.s
.PHONY : vendor/rlImGui/imgui/imgui.cpp.s

vendor/rlImGui/imgui/imgui_draw.o: vendor/rlImGui/imgui/imgui_draw.cpp.o

.PHONY : vendor/rlImGui/imgui/imgui_draw.o

# target to build an object file
vendor/rlImGui/imgui/imgui_draw.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/vendor/rlImGui/imgui/imgui_draw.cpp.o
.PHONY : vendor/rlImGui/imgui/imgui_draw.cpp.o

vendor/rlImGui/imgui/imgui_draw.i: vendor/rlImGui/imgui/imgui_draw.cpp.i

.PHONY : vendor/rlImGui/imgui/imgui_draw.i

# target to preprocess a source file
vendor/rlImGui/imgui/imgui_draw.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/vendor/rlImGui/imgui/imgui_draw.cpp.i
.PHONY : vendor/rlImGui/imgui/imgui_draw.cpp.i

vendor/rlImGui/imgui/imgui_draw.s: vendor/rlImGui/imgui/imgui_draw.cpp.s

.PHONY : vendor/rlImGui/imgui/imgui_draw.s

# target to generate assembly for a file
vendor/rlImGui/imgui/imgui_draw.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/vendor/rlImGui/imgui/imgui_draw.cpp.s
.PHONY : vendor/rlImGui/imgui/imgui_draw.cpp.s

vendor/rlImGui/imgui/imgui_tables.o: vendor/rlImGui/imgui/imgui_tables.cpp.o

.PHONY : vendor/rlImGui/imgui/imgui_tables.o

# target to build an object file
vendor/rlImGui/imgui/imgui_tables.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/vendor/rlImGui/imgui/imgui_tables.cpp.o
.PHONY : vendor/rlImGui/imgui/imgui_tables.cpp.o

vendor/rlImGui/imgui/imgui_tables.i: vendor/rlImGui/imgui/imgui_tables.cpp.i

.PHONY : vendor/rlImGui/imgui/imgui_tables.i

# target to preprocess a source file
vendor/rlImGui/imgui/imgui_tables.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/vendor/rlImGui/imgui/imgui_tables.cpp.i
.PHONY : vendor/rlImGui/imgui/imgui_tables.cpp.i

vendor/rlImGui/imgui/imgui_tables.s: vendor/rlImGui/imgui/imgui_tables.cpp.s

.PHONY : vendor/rlImGui/imgui/imgui_tables.s

# target to generate assembly for a file
vendor/rlImGui/imgui/imgui_tables.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/vendor/rlImGui/imgui/imgui_tables.cpp.s
.PHONY : vendor/rlImGui/imgui/imgui_tables.cpp.s

vendor/rlImGui/imgui/imgui_widgets.o: vendor/rlImGui/imgui/imgui_widgets.cpp.o

.PHONY : vendor/rlImGui/imgui/imgui_widgets.o

# target to build an object file
vendor/rlImGui/imgui/imgui_widgets.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/vendor/rlImGui/imgui/imgui_widgets.cpp.o
.PHONY : vendor/rlImGui/imgui/imgui_widgets.cpp.o

vendor/rlImGui/imgui/imgui_widgets.i: vendor/rlImGui/imgui/imgui_widgets.cpp.i

.PHONY : vendor/rlImGui/imgui/imgui_widgets.i

# target to preprocess a source file
vendor/rlImGui/imgui/imgui_widgets.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/vendor/rlImGui/imgui/imgui_widgets.cpp.i
.PHONY : vendor/rlImGui/imgui/imgui_widgets.cpp.i

vendor/rlImGui/imgui/imgui_widgets.s: vendor/rlImGui/imgui/imgui_widgets.cpp.s

.PHONY : vendor/rlImGui/imgui/imgui_widgets.s

# target to generate assembly for a file
vendor/rlImGui/imgui/imgui_widgets.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/vendor/rlImGui/imgui/imgui_widgets.cpp.s
.PHONY : vendor/rlImGui/imgui/imgui_widgets.cpp.s

vendor/rlImGui/rlImGui.o: vendor/rlImGui/rlImGui.cpp.o

.PHONY : vendor/rlImGui/rlImGui.o

# target to build an object file
vendor/rlImGui/rlImGui.cpp.o:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/vendor/rlImGui/rlImGui.cpp.o
.PHONY : vendor/rlImGui/rlImGui.cpp.o

vendor/rlImGui/rlImGui.i: vendor/rlImGui/rlImGui.cpp.i

.PHONY : vendor/rlImGui/rlImGui.i

# target to preprocess a source file
vendor/rlImGui/rlImGui.cpp.i:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/vendor/rlImGui/rlImGui.cpp.i
.PHONY : vendor/rlImGui/rlImGui.cpp.i

vendor/rlImGui/rlImGui.s: vendor/rlImGui/rlImGui.cpp.s

.PHONY : vendor/rlImGui/rlImGui.s

# target to generate assembly for a file
vendor/rlImGui/rlImGui.cpp.s:
	$(MAKE) -f CMakeFiles/Raytracer.dir/build.make CMakeFiles/Raytracer.dir/vendor/rlImGui/rlImGui.cpp.s
.PHONY : vendor/rlImGui/rlImGui.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Raytracer"
	@echo "... src/AABB.o"
	@echo "... src/AABB.i"
	@echo "... src/AABB.s"
	@echo "... src/AsyncRenderData.o"
	@echo "... src/AsyncRenderData.i"
	@echo "... src/AsyncRenderData.s"
	@echo "... src/Camera.o"
	@echo "... src/Camera.i"
	@echo "... src/Camera.s"
	@echo "... src/GroupPanel.o"
	@echo "... src/GroupPanel.i"
	@echo "... src/GroupPanel.s"
	@echo "... src/HittableList.o"
	@echo "... src/HittableList.i"
	@echo "... src/HittableList.s"
	@echo "... src/Ray.o"
	@echo "... src/Ray.i"
	@echo "... src/Ray.s"
	@echo "... src/RenderAsync.o"
	@echo "... src/RenderAsync.i"
	@echo "... src/RenderAsync.s"
	@echo "... src/Scene.o"
	@echo "... src/Scene.i"
	@echo "... src/Scene.s"
	@echo "... src/Transformation.o"
	@echo "... src/Transformation.i"
	@echo "... src/Transformation.s"
	@echo "... src/app.o"
	@echo "... src/app.i"
	@echo "... src/app.s"
	@echo "... src/data_structures/vec3.o"
	@echo "... src/data_structures/vec3.i"
	@echo "... src/data_structures/vec3.s"
	@echo "... src/editor/Utils.o"
	@echo "... src/editor/Utils.i"
	@echo "... src/editor/Utils.s"
	@echo "... src/editor/editor.o"
	@echo "... src/editor/editor.i"
	@echo "... src/editor/editor.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/objects/AARect.o"
	@echo "... src/objects/AARect.i"
	@echo "... src/objects/AARect.s"
	@echo "... src/objects/Box.o"
	@echo "... src/objects/Box.i"
	@echo "... src/objects/Box.s"
	@echo "... src/objects/Sphere.o"
	@echo "... src/objects/Sphere.i"
	@echo "... src/objects/Sphere.s"
	@echo "... vendor/ImGuiFileDialog/ImGuiFileDialog.o"
	@echo "... vendor/ImGuiFileDialog/ImGuiFileDialog.i"
	@echo "... vendor/ImGuiFileDialog/ImGuiFileDialog.s"
	@echo "... vendor/argumentum/src/argparser.o"
	@echo "... vendor/argumentum/src/argparser.i"
	@echo "... vendor/argumentum/src/argparser.s"
	@echo "... vendor/imguizmo/ImGuizmo.o"
	@echo "... vendor/imguizmo/ImGuizmo.i"
	@echo "... vendor/imguizmo/ImGuizmo.s"
	@echo "... vendor/rlImGui/imgui/backends/imgui_impl_opengl3.o"
	@echo "... vendor/rlImGui/imgui/backends/imgui_impl_opengl3.i"
	@echo "... vendor/rlImGui/imgui/backends/imgui_impl_opengl3.s"
	@echo "... vendor/rlImGui/imgui/imgui.o"
	@echo "... vendor/rlImGui/imgui/imgui.i"
	@echo "... vendor/rlImGui/imgui/imgui.s"
	@echo "... vendor/rlImGui/imgui/imgui_draw.o"
	@echo "... vendor/rlImGui/imgui/imgui_draw.i"
	@echo "... vendor/rlImGui/imgui/imgui_draw.s"
	@echo "... vendor/rlImGui/imgui/imgui_tables.o"
	@echo "... vendor/rlImGui/imgui/imgui_tables.i"
	@echo "... vendor/rlImGui/imgui/imgui_tables.s"
	@echo "... vendor/rlImGui/imgui/imgui_widgets.o"
	@echo "... vendor/rlImGui/imgui/imgui_widgets.i"
	@echo "... vendor/rlImGui/imgui/imgui_widgets.s"
	@echo "... vendor/rlImGui/rlImGui.o"
	@echo "... vendor/rlImGui/rlImGui.i"
	@echo "... vendor/rlImGui/rlImGui.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

